# Generated by Django 5.1.6 on 2025-02-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_rename_time_slot_reservation_time_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='reservation',
            name='time_slots',
            field=models.ManyToManyField(to='reservations.timeslot'),
        ),
    ]
